#!/bin/bash
echo "To upload FCM v1 credentials, run:"
echo ""
echo "eas credentials"
echo ""
echo "Then select:"
echo "1. Android"
echo "2. Push Notifications: Manage your FCM Api Key" 
echo "3. Set up a Google Service Account Key for Push Notifications (FCM V1)"
echo "4. Upload a new service account key"
echo "5. Select: shasthohive-firebase-adminsdk-fbsvc-ace6bfa503.json"
echo ""
echo "Or use the EAS dashboard:"
echo "https://expo.dev/accounts/[your-account]/projects/client/credentials"
